root: true
owner: Adam Jenkins
start_year: 2026
substring: This file is part of
template: |-
  {comment_start} This file is part of the Show Me The Money plugin for Indico.
  {comment_middle} Copyright (C) {dates} {owner}
  {comment_middle}
  {comment_middle} The Show Me The Money plugin is free software; you can redistribute
  {comment_middle} it and/or modify it under the terms of the MIT License;
  {comment_middle} see the LICENSE file for more details.
  {comment_end}
