[pytest]
addopts = -rsfEw
python_files = *_test.py
indico_plugins = showmethemoney
norecursedirs = indico-src
filterwarnings =
    error
    ignore::sqlalchemy.exc.SAWarning
    ignore::UserWarning
redis_exec = redis-server
